### ISSUE TITLE
Error creating project, XSRF check failed

### ISSUE THREAD

**Issue by Delavor** [EugenMayer/docker-image-atlassian-jira#2]
Hi, i'm using traefik reverse proxy and when i'm trying to create any project after submit i got error
```Error creating project, XSRF check failed```

It's probably problem with mixed-content because loading elements from http, should from https.

**Comment by EugenMayer** [comment]
Sorry but that are all atlassian questions, not docker image related :)

Beside that, we are using traefik too, just that you know

**Comment by EugenMayer** [comment]
see https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/jira/36/docker-compose.yml#L23 for a raugh idea
