### ISSUE TITLE
Suggestion: AdoptJre11 version (openj9?)

### ISSUE THREAD

**Issue by unquietwiki** [EugenMayer/docker-image-atlassian-jira#3]
* https://github.com/AdoptOpenJDK/openjdk-docker
* https://hub.docker.com/r/atlassian/confluence-server/tags

The official Confluence build has had Alpine-based OpenJDK8 versions since at least 6.13; no reason why Jira shouldn't work with it.

**Comment by EugenMayer** [comment]
Changed title to AdoptJre 11 since with 8.2 we finally have support for that. I will most probably fork the Dockerfile for 8.2+ and the one for below, offering a openj9 based jre3 image, either alpine or ubuntu based

**Comment by EugenMayer** [comment]
Adopted it today, openj9 is a nogo since atlassian uses js based optimizations on startup. Beside that, i removed all the dust and it is based on debian buster rather then alpine now
