### ISSUE TITLE
The database collation 'utf8mb4_bin' and table collation 'utf8mb4_general_ci' are not supported by Jira.

### ISSUE THREAD

**Issue by romancin** [EugenMayer/docker-image-atlassian-jira#5]
Hi! I have just migrated to a new installation with a clean database. As I am using mysql 5.7 Ihave configured the collation as stated by Atlassian for this database:

https://confluence.atlassian.com/adminjiraserver/connecting-jira-applications-to-mysql-5-7-966063305.html#ConnectingJiraapplicationstoMySQL5.7-dbconnectionfields

But using your image, I have an error on the Health Check saying the collation is not supported:
![image](https://user-images.githubusercontent.com/17579835/70822800-b41d8480-1dde-11ea-87c9-d225882751b1.png)

After investigating it, it is probably by this reason:
![image](https://user-images.githubusercontent.com/17579835/70822947-09599600-1ddf-11ea-854c-56df0b83c11b.png)

It would be possible to set this value using an environment variable for example in order to fix it? Thank you!

**Comment by EugenMayer** [comment]
Sure, that should be possible without bigger issue

**Comment by romancin** [comment]
Awesome, thank you!

**Comment by EugenMayer** [comment]
fixed

**Comment by romancin** [comment]
Working, thank you!
